security:
  api-key: "pubaA6JW4SQsJX37jsLxWCnP72FUTChMuJlxuVWyqaiyACHt52rPzJpZFcyISf7Y"
  jwt-secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  jwt-expiration-ms: 900000 # 900,000 milliseconds (15 minutes)
  jwt-refresh-expiration-ms : 86400000 # 86,400,000 milliseconds (24 hours)


spring:
  datasource:
    username: mothkiller99
    url: jdbc:postgresql://dpg-crbh7vlds78s73dfnh5g-a.frankfurt-postgres.render.com/pubservice
    password: kBzT7yaIQxEPL7Bp1TymPWeyFQsUyrDv
#server:
#  ssl:
#    key-store-password: "Himlen@rGr0n"
#    key-password: "Himlen@rGr0n"
#    keyStoreType: "PKCS12"
#    keyAlias: "pubfinder"